import { createElement } from '@lwc/engine-dom';
import EventDashboard from 'c/eventDashboard';

describe('c-event-dashboard', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-event-dashboard', {
            is: EventDashboard
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});