import { createElement } from '@lwc/engine-dom';
import LoyaltyRewardStore from 'c/loyaltyRewardStore';

describe('c-loyalty-reward-store', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-loyalty-reward-store', {
            is: LoyaltyRewardStore
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});