import { createElement } from '@lwc/engine-dom';
import TeamSocialLinks from 'c/teamSocialLinks';

describe('c-team-social-links', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-team-social-links', {
            is: TeamSocialLinks
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});