import { createElement } from '@lwc/engine-dom';
import StadiumSeatMap from 'c/stadiumSeatMap';

describe('c-stadium-seat-map', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-stadium-seat-map', {
            is: StadiumSeatMap
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});