import { createElement } from '@lwc/engine-dom';
import VerticalNavPanel from 'c/verticalNavPanel';

describe('c-vertical-nav-panel', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-vertical-nav-panel', {
            is: VerticalNavPanel
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});