import { createElement } from '@lwc/engine-dom';
import SeasonPassManager from 'c/seasonPassManager';

describe('c-season-pass-manager', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-season-pass-manager', {
            is: SeasonPassManager
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});