import { createElement } from '@lwc/engine-dom';
import FanManager from 'c/fanManager';

describe('c-fan-manager', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-fan-manager', {
            is: FanManager
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});