import { createElement } from '@lwc/engine-dom';
import HotEventsTicker from 'c/hotEventsTicker';

describe('c-hot-events-ticker', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-hot-events-ticker', {
            is: HotEventsTicker
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});