import { createElement } from '@lwc/engine-dom';
import FanProfileCard from 'c/fanProfileCard';

describe('c-fan-profile-card', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-fan-profile-card', {
            is: FanProfileCard
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});