import { createElement } from '@lwc/engine-dom';
import CancelOrderButton from 'c/cancelOrderButton';

describe('c-cancel-order-button', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-cancel-order-button', {
            is: CancelOrderButton
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});