import { createElement } from '@lwc/engine-dom';
import PaymentCardSimulator from 'c/paymentCardSimulator';

describe('c-payment-card-simulator', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-payment-card-simulator', {
            is: PaymentCardSimulator
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});