import { createElement } from '@lwc/engine-dom';
import StadiumWeather from 'c/stadiumWeather';

describe('c-stadium-weather', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-stadium-weather', {
            is: StadiumWeather
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});