import { createElement } from '@lwc/engine-dom';
import FanLoyaltyWidget from 'c/fanLoyaltyWidget';

describe('c-fan-loyalty-widget', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-fan-loyalty-widget', {
            is: FanLoyaltyWidget
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});