import { createElement } from '@lwc/engine-dom';
import SportEventList from 'c/sportEventList';

describe('c-sport-event-list', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-sport-event-list', {
            is: SportEventList
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});