import { createElement } from '@lwc/engine-dom';
import LanguageCurrencySelector from 'c/languageCurrencySelector';

describe('c-language-currency-selector', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-language-currency-selector', {
            is: LanguageCurrencySelector
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});