import { createElement } from '@lwc/engine-dom';
import SportDetail from 'c/sportDetail';

describe('c-sport-detail', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-sport-detail', {
            is: SportDetail
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});