import { createElement } from '@lwc/engine-dom';
import CurrentChampion from 'c/currentChampion';

describe('c-current-champion', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-current-champion', {
            is: CurrentChampion
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});