import { createElement } from '@lwc/engine-dom';
import SfAiAgent from 'c/sfAiAgent';

describe('c-sf-ai-agent', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-sf-ai-agent', {
            is: SfAiAgent
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});