import { createElement } from '@lwc/engine-dom';
import TicketQRDisplay from 'c/ticketQRDisplay';

describe('c-ticket-qr-display', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-ticket-qr-display', {
            is: TicketQRDisplay
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});